name: ferry_issue
description: Ferry Graphql Issue
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'
  ferry: #[latest-version]
  gql_http_link: #[latest-version]

dependencies:
  path: ^1.8.0
  ferry: #[latest-version]
  gql_http_link: #[latest-version]

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ferry_generator: #[latest-version]
  build_runner: #[latest-version]
